class CfgPatches {class tsp_rhs_ech {requiredAddons[] = {"rhs_infantry"}; units[] = {};};};

class CfgWeapons {
	class rhsusf_ach_helmet_ocp; class rhsusf_ach_helmet_ocp_alt;
	class rhsusf_ach_helmet_ESS_ocp; class rhsusf_ach_helmet_ESS_ocp_alt;
	class rhsusf_ach_helmet_headset_ocp; class rhsusf_ach_helmet_headset_ocp_alt;
	class rhsusf_ach_helmet_headset_ess_ocp; class rhsusf_ach_helmet_headset_ess_ocp_alt;
	class rhsusf_ach_helmet_camo_ocp; class rhsusf_ach_helmet_ocp_norotos;	
	class rhsusf_ach_helmet_marpatd: rhsusf_ach_helmet_ocp {displayName = "ECH MARPAT-D"; hiddenSelectionsTextures[] = {"\rhsusf\addons\rhsusf_infantry\gear\head\data\mich_covered_rhino_des_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\ach_acc_tan_co.paa"}; picture = "\rhsusf\addons\rhsusf_inventoryicons\data\headgear\rhsusf_mich_helmet_marpatd_ca.paa";};
	class rhsusf_ach_helmet_marpatd_alt: rhsusf_ach_helmet_ocp_alt {displayName = "ECH MARPAT-D (Alt)"; hiddenSelectionsTextures[] = {"\rhsusf\addons\rhsusf_infantry\gear\head\data\mich_covered_rhino_des_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\rhs_helmet_ach_acc_co.paa"}; picture = "\rhsusf\addons\rhsusf_inventoryicons\data\headgear\rhsusf_mich_helmet_marpatd_ca.paa";};
	class rhsusf_ach_helmet_ess_marpatd: rhsusf_ach_helmet_ESS_ocp {displayName = "ECH MARPAT-D (ESS)"; hiddenSelectionsTextures[] = {"\rhsusf\addons\rhsusf_infantry\gear\head\data\mich_covered_rhino_des_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\ach_acc_tan_co.paa"}; picture = "\rhsusf\addons\rhsusf_inventoryicons\data\headgear\rhsusf_mich_helmet_marpatd_ca.paa";};
	class rhsusf_ach_helmet_ess_marpatd_alt: rhsusf_ach_helmet_ESS_ocp_alt {displayName = "ECH MARPAT-D (ESS/Alt)"; hiddenSelectionsTextures[] = {"\rhsusf\addons\rhsusf_infantry\gear\head\data\mich_covered_rhino_des_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\rhs_helmet_ach_acc_co.paa"}; picture = "\rhsusf\addons\rhsusf_inventoryicons\data\headgear\rhsusf_mich_helmet_marpatd_ca.paa";};
	class rhsusf_ach_helmet_headset_marpatd: rhsusf_ach_helmet_headset_ocp {displayName = "ECH MARPAT-D (Headset)"; hiddenSelectionsTextures[] = {"\rhsusf\addons\rhsusf_infantry\gear\head\data\mich_covered_rhino_des_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\ach_acc_tan_co.paa"}; picture = "\rhsusf\addons\rhsusf_inventoryicons\data\headgear\rhsusf_mich_helmet_marpatd_ca.paa";};
	class rhsusf_ach_helmet_headset_marpatd_alt: rhsusf_ach_helmet_headset_ocp_alt {displayName = "ECH MARPAT-D (Headset/Alt)"; hiddenSelectionsTextures[] = {"\rhsusf\addons\rhsusf_infantry\gear\head\data\mich_covered_rhino_des_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\rhs_helmet_ach_acc_co.paa"}; picture = "\rhsusf\addons\rhsusf_inventoryicons\data\headgear\rhsusf_mich_helmet_marpatd_ca.paa";};
	class rhsusf_ach_helmet_headset_ess_marpatd: rhsusf_ach_helmet_headset_ess_ocp {displayName = "ECH MARPAT-D (Headset/ESS)"; hiddenSelectionsTextures[] = {"\rhsusf\addons\rhsusf_infantry\gear\head\data\mich_covered_rhino_des_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\ach_acc_tan_co.paa"}; picture = "\rhsusf\addons\rhsusf_inventoryicons\data\headgear\rhsusf_mich_helmet_marpatd_ca.paa";};
	class rhsusf_ach_helmet_headset_ess_marpatd_alt: rhsusf_ach_helmet_headset_ess_ocp_alt {displayName = "ECH MARPAT-D (Headset/ESS/Alt)"; hiddenSelectionsTextures[] = {"\rhsusf\addons\rhsusf_infantry\gear\head\data\mich_covered_rhino_des_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\rhs_helmet_ach_acc_co.paa"}; picture = "\rhsusf\addons\rhsusf_inventoryicons\data\headgear\rhsusf_mich_helmet_marpatd_ca.paa";};
	class rhsusf_ach_helmet_camo_marpatd: rhsusf_ach_helmet_camo_ocp {displayName = "ECH MARPAT-D (Netting)"; hiddenSelectionsTextures[] = {"\rhsusf\addons\rhsusf_infantry\gear\head\data\mich_covered_rhino_des_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\ach_acc_tan_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\camo_net_co.paa"}; picture = "\rhsusf\addons\rhsusf_inventoryicons\data\headgear\rhsusf_mich_helmet_marpatd_ca.paa";};
	class rhsusf_ach_helmet_marpatd_norotos: rhsusf_ach_helmet_ocp_norotos {displayName = "ECH MARPAT-D (Norotos)"; hiddenSelectionsTextures[] = {"\rhsusf\addons\rhsusf_infantry\gear\head\data\mich_covered_rhino_des_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\ach_acc_tan_co.paa"}; picture = "\rhsusf\addons\rhsusf_inventoryicons\data\headgear\rhsusf_mich_helmet_marpatd_ca.paa";};
	class rhsusf_ach_helmet_marpatwd: rhsusf_ach_helmet_ocp {displayName = "ECH MARPAT-WD"; hiddenSelectionsTextures[] = {"\rhsusf\addons\rhsusf_infantry\gear\head\data\mich_covered_rhino_wd_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\ach_acc_tan_co.paa"}; picture = "\rhsusf\addons\rhsusf_inventoryicons\data\headgear\rhsusf_mich_helmet_marpatwd_ca.paa";};
	class rhsusf_ach_helmet_marpatwd_alt: rhsusf_ach_helmet_ocp_alt {displayName = "ECH MARPAT-WD (Alt)"; hiddenSelectionsTextures[] = {"\rhsusf\addons\rhsusf_infantry\gear\head\data\mich_covered_rhino_wd_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\rhs_helmet_ach_acc_co.paa"}; picture = "\rhsusf\addons\rhsusf_inventoryicons\data\headgear\rhsusf_mich_helmet_marpatwd_ca.paa";};
	class rhsusf_ach_helmet_ess_marpatwd: rhsusf_ach_helmet_ESS_ocp {displayName = "ECH MARPAT-WD (ESS)"; hiddenSelectionsTextures[] = {"\rhsusf\addons\rhsusf_infantry\gear\head\data\mich_covered_rhino_wd_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\ach_acc_tan_co.paa"}; picture = "\rhsusf\addons\rhsusf_inventoryicons\data\headgear\rhsusf_mich_helmet_marpatwd_ca.paa";};
	class rhsusf_ach_helmet_ess_marpatwd_alt: rhsusf_ach_helmet_ESS_ocp_alt {displayName = "ECH MARPAT-WD (ESS/Alt)"; hiddenSelectionsTextures[] = {"\rhsusf\addons\rhsusf_infantry\gear\head\data\mich_covered_rhino_wd_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\rhs_helmet_ach_acc_co.paa"}; picture = "\rhsusf\addons\rhsusf_inventoryicons\data\headgear\rhsusf_mich_helmet_marpatwd_ca.paa";};
	class rhsusf_ach_helmet_headset_marpatwd: rhsusf_ach_helmet_headset_ocp {displayName = "ECH MARPAT-WD (Headset)"; hiddenSelectionsTextures[] = {"\rhsusf\addons\rhsusf_infantry\gear\head\data\mich_covered_rhino_wd_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\ach_acc_tan_co.paa"}; picture = "\rhsusf\addons\rhsusf_inventoryicons\data\headgear\rhsusf_mich_helmet_marpatwd_ca.paa";};
	class rhsusf_ach_helmet_headset_marpatwd_alt: rhsusf_ach_helmet_headset_ocp_alt {displayName = "ECH MARPAT-WD (Headset/Alt)"; hiddenSelectionsTextures[] = {"\rhsusf\addons\rhsusf_infantry\gear\head\data\mich_covered_rhino_wd_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\rhs_helmet_ach_acc_co.paa"}; picture = "\rhsusf\addons\rhsusf_inventoryicons\data\headgear\rhsusf_mich_helmet_marpatwd_ca.paa";};
	class rhsusf_ach_helmet_headset_ess_marpatwd: rhsusf_ach_helmet_headset_ess_ocp {displayName = "ECH MARPAT-WD (Headset/ESS)"; hiddenSelectionsTextures[] = {"\rhsusf\addons\rhsusf_infantry\gear\head\data\mich_covered_rhino_wd_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\ach_acc_tan_co.paa"}; picture = "\rhsusf\addons\rhsusf_inventoryicons\data\headgear\rhsusf_mich_helmet_marpatwd_ca.paa";};
	class rhsusf_ach_helmet_headset_ess_marpatwd_alt: rhsusf_ach_helmet_headset_ess_ocp_alt {displayName = "ECH MARPAT-WD (Headset/ESS/Alt)"; hiddenSelectionsTextures[] = {"\rhsusf\addons\rhsusf_infantry\gear\head\data\mich_covered_rhino_wd_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\rhs_helmet_ach_acc_co.paa"}; picture = "\rhsusf\addons\rhsusf_inventoryicons\data\headgear\rhsusf_mich_helmet_marpatwd_ca.paa";};
	class rhsusf_ach_helmet_camo_marpatwd: rhsusf_ach_helmet_camo_ocp {displayName = "ECH MARPAT-WD (Netting)"; hiddenSelectionsTextures[] = {"\rhsusf\addons\rhsusf_infantry\gear\head\data\mich_covered_rhino_wd_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\ach_acc_tan_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\camo_net_co.paa"}; picture = "\rhsusf\addons\rhsusf_inventoryicons\data\headgear\rhsusf_mich_helmet_marpatwd_ca.paa";};
	class rhsusf_ach_helmet_marpatwd_norotos: rhsusf_ach_helmet_ocp_norotos {displayName = "ECH MARPAT-WD (Norotos)"; hiddenSelectionsTextures[] = {"\rhsusf\addons\rhsusf_infantry\gear\head\data\mich_covered_rhino_wd_co.paa", "\rhsusf\addons\rhsusf_infantry\gear\head\data\ach_acc_tan_co.paa"}; picture = "\rhsusf\addons\rhsusf_inventoryicons\data\headgear\rhsusf_mich_helmet_marpatwd_ca.paa";};
};